@host = http://localhost:8084

###
GET  {{ host }}/message
Content-Type: application/json

{}

###
GET  http://localhost:8082/message
Content-Type: application/json

{}

###
POST  {{ host }}/actuator/bus-refresh
Content-Type: application/json

{}

###
POST  {{ host }}/env
Content-Type: application/json

{}
