@host = http://localhost:8084

###
GET  {{ host }}/message
Content-Type: application/json

{}

###
GET  http://localhost:8082/message
Content-Type: application/json

{}

###
POST  http://localhost:8081/actuator/busrefresh
Content-Type: application/json

{}

###
POST  {{ host }}/env
Content-Type: application/json

{}
